// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ar_taylor_cpp
List ar_taylor_cpp(int p, int q, NumericMatrix seeds);
RcppExport SEXP _parameters7_ar_taylor_cpp(SEXP pSEXP, SEXP qSEXP, SEXP seedsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type seeds(seedsSEXP);
    rcpp_result_gen = Rcpp::wrap(ar_taylor_cpp(p, q, seeds));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_parameters7_ar_taylor_cpp", (DL_FUNC) &_parameters7_ar_taylor_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_parameters7(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
