# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ar_taylor_cpp <- function(p, q, seeds) {
    .Call(`_parameters7_ar_taylor_cpp`, p, q, seeds)
}

chol_leibniz_cpp <- function(p, tuples, row, col, ondiag, L, free_names, dim_names) {
    .Call(`_parameters7_chol_leibniz_cpp`, p, tuples, row, col, ondiag, L, free_names, dim_names)
}

