# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ar_value_cpp <- function(p, q, seeds) {
    .Call(`_parameters7_ar_value_cpp`, p, q, seeds)
}

ar_d1_cpp <- function(p, q, seeds, tuples) {
    .Call(`_parameters7_ar_d1_cpp`, p, q, seeds, tuples)
}

ar_d2_cpp <- function(p, q, seeds, tuples) {
    .Call(`_parameters7_ar_d2_cpp`, p, q, seeds, tuples)
}

ar_d3_cpp <- function(p, q, seeds, tuples) {
    .Call(`_parameters7_ar_d3_cpp`, p, q, seeds, tuples)
}

ar_d4_cpp <- function(p, q, seeds, tuples) {
    .Call(`_parameters7_ar_d4_cpp`, p, q, seeds, tuples)
}

ar_toeplitz_cpp <- function(g, nm) {
    .Call(`_parameters7_ar_toeplitz_cpp`, g, nm)
}

ar_taylor_jet_cpp <- function(p, q, seeds, K) {
    .Call(`_parameters7_ar_taylor_jet_cpp`, p, q, seeds, K)
}

chol_leibniz_cpp <- function(p, tuples, row, col, ondiag, L, free_names, dim_names) {
    .Call(`_parameters7_chol_leibniz_cpp`, p, tuples, row, col, ondiag, L, free_names, dim_names)
}

